Added dockerfile

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -114,12 +114,68 @@ jobs:
     environment:
       name: production
       url: https://e-commerce-api-ts.onrender.com
+    permissions:
+      contents: write
 
     steps:
-      -  name: Deploy no Render
-         env:
+      - name: Deploy no Render
+        env:
           RENDER_PROD_HOOK_URL: ${{ secrets.RENDER_PROD_HOOK_URL }}
-         run: |
+        run: |
           echo "Deploying to PRODUCTION environment..."
           curl -X POST $RENDER_PROD_HOOK_URL
           echo "🚀 Production deploy initiated"
+
+    # Espera o deploy completar para seguir com o próximo passo
+      - name: Wait for deployment to complete
+        run: |
+          echo "Waiting for deployment"
+          sleep 90
+        
+        # Checagem da aplicação
+      - name: Health check production
+        id: prod_health_check
+        env:
+          PROD_URL: ${{ secrets.PROD_URL || 'https://e-commerce-api-ts.onrender.com' }}
+        run: |
+          echo "Checking aplication's health"
+          
+          for i in {1..3}; do
+            echo "attempt $i/3..."
+            if curl -f -s --max-time 30 "$PROD_URL/api/v1/health" || curl -f -s --max-time 30 "$PROD_URL/api/v1/products"; then
+              echo "Production health check passed"
+              exit 0
+            fi
+            sleep 10
+          done
+          
+          echo "Health check failed after 3 attempts"
+          exit 1
+      
+      # Baixa o código pra VM apenas se o health check falhar
+      - name: Checkout code for rollback
+        if: failure() && steps.prod_health_check.outcome == 'failure'
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      # Rollback se der falha no passo anterior
+      - name: Rollback production
+        if: failure() && steps.prod_health_check.outcome == 'failure'
+        env:
+          GITHUB_TOKEN: ${{ secrets.PAT_FOR_ROLLBACK }}
+          RENDER_PROD_HOOK_URL: ${{ secrets.RENDER_PROD_HOOK_URL }}
+        run: |
+          echo "Health check failed, initializing rollback"
+
+          git config --global user.email "rdgoliv18@gmail.com"
+          git config --global user.name "rodoliv98"
+
+          git revert --no-edit ${{ github.sha }}
+          git push origin master
+
+          sleep 20
+
+          echo "Starting rollback deploy"
+          curl -X POST $RENDER_PROD_HOOK_URL
+          echo "Rollback done, previous version failed while deployed"
